# Generated by Django 5.2.6 on 2025-09-18 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_wishlist', models.BooleanField(default=True, help_text='Enable/disable wishlist functionality site-wide')),
                ('allow_guest_wishlist', models.BooleanField(default=False, help_text='Allow non-logged in users to use wishlist (stored in session)')),
                ('max_wishlist_items', models.PositiveIntegerField(default=100, help_text='Maximum number of items allowed in a wishlist (0 = unlimited)')),
                ('show_wishlist_count', models.BooleanField(default=True, help_text='Show wishlist item count in navigation')),
                ('enable_wishlist_sharing', models.BooleanField(default=True, help_text='Allow users to share their wishlist with others')),
                ('wishlist_expiry_days', models.PositiveIntegerField(default=365, help_text='Number of days after which inactive wishlist items expire (0 = never expire)')),
            ],
            options={
                'verbose_name': 'Wishlist Settings',
                'verbose_name_plural': 'Wishlist Settings',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['-added_at'],
                'unique_together': {('wishlist', 'product')},
            },
        ),
    ]
