"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SITE_NAME = "SmokeKing"  # or whatever your brand/site name is


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pwy17m*qf)8l%@#_gf!tp+-$!a-@=k^dd@gqvtvyku%$^8#c@$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'store',
    'accounts',
    'payments',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # ✅ Custom context processor to inject categories globally
                'store.context_processors.categories_processor',
                'store.context_processors.cart_info',
                'store.context_processors.site_name',
                'store.context_processors.site_settings',


            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

import os

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/gallery/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'gallery')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.CustomUser'



PHONEPE_CLIENT_ID = "SU2507292038248008993570"
PHONEPE_CLIENT_SECRET = "0e406203-cdd0-4292-99dc-9a52e8b35888"
PHONEPE_CLIENT_VERSION = 1  # Usually 1 unless PhonePe instructs otherwise

# ENV
PHONEPE_ENV = "PRODUCTION"  # or "SANDBOX" if you're still testing

# CALLBACK AUTH (Webhook Security)
PHONEPE_USERNAME = "smokeking"           # Same as configured in PhonePe webhook
PHONEPE_PASSWORD = "comdeveloperse2E"    # Same as configured in PhonePe webhook

# URLs
PHONEPE_REDIRECT_URL = "https://smokeking.in/payments/redirect/"
PHONEPE_CALLBACK_URL = "https://smokeking.in/payments/callback/"



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'  # or your provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'noreply@smokeking.in'
ADMIN_NOTIFICATION_EMAIL = 'rajat@quikprof.com'
EMAIL_HOST_PASSWORD = 't$xf8lwcqT1'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ─────────────────────────────
# 🛍️ GOOGLE MERCHANT CENTER SETTINGS
# ─────────────────────────────

# Site URL for feed generation
SITE_URL = 'https://smokeking.in'

# Google Merchant Center Settings
GOOGLE_MERCHANT_CENTER = {
    'MERCHANT_ID': '5633074318',  # Your Google Merchant Center ID
    'FEED_TITLE': f'{SITE_NAME} - Product Feed',
    'FEED_DESCRIPTION': f'Product feed for {SITE_NAME} - Premium smoking accessories',
    'DEFAULT_BRAND': SITE_NAME,
    'DEFAULT_CONDITION': 'new',
    'DEFAULT_AVAILABILITY': 'in stock',
    'SHIPPING_COUNTRY': 'IN',
    'SHIPPING_SERVICE': 'Standard',
    'SHIPPING_PRICE': '0 INR',  # Free shipping
    'AGE_GROUP': 'adult',
    'GENDER': 'unisex',
    'CURRENCY': 'INR',
    
    # Category mapping to Google's taxonomy
    'CATEGORY_MAPPING': {
        'lighters': 'Home & Garden > Smoking Accessories > Lighters',
        'ashtrays': 'Home & Garden > Smoking Accessories > Ashtrays',
        'cigar accessories': 'Home & Garden > Smoking Accessories > Cigar Accessories',
        'pipes': 'Home & Garden > Smoking Accessories > Pipes',
        'rolling papers': 'Home & Garden > Smoking Accessories > Rolling Papers',
        'vaporizers': 'Electronics > Electronics Accessories > Electronic Cigarettes & Vaporizers',
        'grinders': 'Home & Garden > Smoking Accessories',
        'storage': 'Home & Garden > Household Supply Storage',
    },
    
    # Feed generation settings
    'MAX_PRODUCTS': 10000,  # Maximum products in feed
    'MAX_ADDITIONAL_IMAGES': 10,  # Maximum additional images per product
    'DESCRIPTION_MAX_LENGTH': 5000,
    'TITLE_MAX_LENGTH': 150,
}

# Google API Settings (for Content API integration)
GOOGLE_API = {
    'SERVICE_ACCOUNT_FILE': '',  # Path to your service account JSON file
    'APPLICATION_NAME': f'{SITE_NAME} - Google Shopping Integration',
}
