# Generated by Django 4.2.23 on 2025-07-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
