# Generated by Django 4.2.18 on 2025-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_banner_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='initiated', max_length=20),
        ),
    ]
