# Generated by Django 4.2.18 on 2025-07-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mobile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/categories/banners/mobile/'),
        ),
    ]
