# Generated by Django 4.2.21 on 2025-08-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_order_shipping_address_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid on delivery for COD orders', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery')], default='online', max_length=20),
        ),
    ]
