# Generated by Django 4.2.21 on 2025-09-05 07:12

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_seller_remark_order_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gif',
            field=models.ImageField(blank=True, help_text='Animated GIF to show on hover', null=True, upload_to=store.models.Product.product_gif_upload_path),
        ),
    ]
