# Generated by Django 4.2.21 on 2025-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_category_banner_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonePeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_id', models.CharField(max_length=64, unique=True)),
                ('phonepe_order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(default='INITIATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='PhonePeRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_refund_id', models.CharField(max_length=64, unique=True)),
                ('refund_id', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(default='INITIATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phonepe_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.phonepeorder')),
            ],
        ),
    ]
