# Generated by Django 5.2.5 on 2025-09-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_currency_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Ecom_CMS', help_text='Name of your website', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('default', 'Default Theme'), ('modern', 'Modern Theme'), ('glam', 'Glam Theme'), ('smoke', 'Smoke Theme')], default='glam', help_text='Visual theme for your website', max_length=20),
        ),
    ]
