# Generated by Django 5.2.6 on 2025-09-18 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('release_date', models.DateTimeField()),
                ('download_url', models.URLField()),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('checksum', models.CharField(max_length=64)),
                ('critical', models.BooleanField(default=False)),
                ('beta', models.BooleanField(default=False)),
                ('min_version_required', models.CharField(blank=True, help_text='Minimum version required for this update', max_length=50)),
                ('release_notes', models.TextField(blank=True)),
                ('compatibility_notes', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('installed', models.BooleanField(default=False)),
                ('install_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Available Update',
                'verbose_name_plural': 'Available Updates',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='UpdateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('current_version', models.CharField(max_length=50)),
                ('latest_version', models.CharField(blank=True, max_length=50)),
                ('update_available', models.BooleanField(default=False)),
                ('critical_update', models.BooleanField(default=False)),
                ('check_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Update Check',
                'verbose_name_plural': 'Update Checks',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='UpdateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('update_available', 'Update Available'), ('critical_update', 'Critical Update'), ('update_completed', 'Update Completed'), ('update_failed', 'Update Failed'), ('backup_created', 'Backup Created')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_version', models.CharField(blank=True, max_length=50)),
                ('action_url', models.URLField(blank=True)),
                ('action_label', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Update Notification',
                'verbose_name_plural': 'Update Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_check_enabled', models.BooleanField(default=True, help_text='Automatically check for updates')),
                ('auto_install_enabled', models.BooleanField(default=False, help_text='Automatically install non-critical updates')),
                ('check_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual Only')], default='weekly', help_text='How often to check for updates', max_length=20)),
                ('install_critical_updates', models.BooleanField(default=True, help_text='Automatically install critical security updates')),
                ('backup_before_update', models.BooleanField(default=True, help_text='Create backup before applying updates')),
                ('max_backups_to_keep', models.PositiveIntegerField(default=5, help_text='Maximum number of backups to keep')),
                ('update_server_url', models.URLField(default='https://api.yoursite.com/cms-updates', help_text='URL of the update server')),
                ('api_key', models.CharField(blank=True, help_text='API key for update server (if required)', max_length=255)),
                ('notification_email', models.EmailField(blank=True, help_text='Email to notify about available updates', max_length=254)),
                ('beta_updates', models.BooleanField(default=False, help_text='Include beta/pre-release updates')),
            ],
            options={
                'verbose_name': 'Update Settings',
                'verbose_name_plural': 'Update Settings',
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('from_version', models.CharField(max_length=50)),
                ('to_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('backing_up', 'Creating Backup'), ('installing', 'Installing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('auto_update', models.BooleanField(default=False, help_text='Whether this was an automatic update')),
                ('backup_path', models.CharField(blank=True, max_length=500)),
                ('download_size', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated the update', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update Log',
                'verbose_name_plural': 'Update Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
