# Generated by Django 4.2.21 on 2025-09-20 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_check_enabled', models.BooleanField(default=True, help_text='Automatically check for updates')),
                ('check_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('include_prereleases', models.BooleanField(default=False, help_text='Include pre-release versions')),
            ],
            options={
                'verbose_name': 'Update Settings',
                'verbose_name_plural': 'Update Settings',
            },
        ),
        migrations.CreateModel(
            name='VersionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.CharField(max_length=100)),
                ('latest_version', models.CharField(blank=True, max_length=100)),
                ('update_available', models.BooleanField(default=False)),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Version Check',
                'verbose_name_plural': 'Version Checks',
                'ordering': ['-check_date'],
            },
        ),
    ]
