# Generated by Django 4.2.21 on 2025-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesettings',
            name='api_key',
            field=models.CharField(blank=True, help_text='GitHub token for higher API rate limits (optional but recommended)', max_length=255),
        ),
        migrations.AlterField(
            model_name='updatesettings',
            name='update_server_url',
            field=models.URLField(default='https://api.github.com/repos/studsu/ecom_CMS/releases', help_text='GitHub releases API URL (leave as default for automatic GitHub integration)'),
        ),
    ]
