# Generated by Django 5.2.5 on 2025-09-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product_variant_orderitem_variant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
